### ISSUE TITLE
Facing issue related Timeline and program syncing

### ISSUE THREAD

**Issue by khushbuThakker** [egeniq/android-tv-program-guide#11]
Hello,
I am facing the issue when setting the time in timeline row from 12:00 AM to the end of the day at 23.59PM.
Could anyone please suggest how to do this? 

as I already changed the parameter of "
        private const val DAY_STARTS_AT_HOUR = 1
        private const val DAY_ENDS_NEXT_DAY_AT_HOUR = 2" in "ProgramGuideManager" file but no effect reflection is visible.

I have added my live data inside that so because this start time issue, I am not able to show the correct current program.

It will help me a lot if anyone can help me.

Thanks in advance.

**Comment by dzolnai** [comment]
Hi!

What do you mean specifically with 12AM? Let's use the 24 hour format :)
Do you want your day to start at 0:00 and end at 24:00?
Or at 12:00 (noon) until the next day at 12:00?

Also make sure that all timezones are in sync, that can lead to hour differences.

**Comment by khushbuThakker** [comment]
Yes, the meaning is 0 to the next 23 hours but when I set this still the timeline starting from 5

**Comment by dzolnai** [comment]
In that case you should use the following settings:

```
private const val DAY_STARTS_AT_HOUR = 0
private const val DAY_ENDS_NEXT_DAY_AT_HOUR = 0
```
If you want to test it in the test EpgFragment, you also should change the min channel time.
```
val MIN_CHANNEL_START_TIME = localDate.atStartOfDay().withHour(0).truncatedTo(ChronoUnit.HOURS).atZone(DISPLAY_TIMEZONE)
```

**Comment by khushbuThakker** [comment]
Hello @dzolnai ,
I have tried the above solution  and setup this :
private const Val DAY_STARTS_AT_HOUR = 0
private const Val DAY_ENDS_NEXT_DAY_AT_HOUR = 0
but still not start from 0 hours.

Because of this timeline, my dynamic program not syncing with the time.

**Comment by dzolnai** [comment]
Please note that it will not start at 0 hours if any of your programs do not start then.
So let's say the first program start at 04:30. You will not be able to scroll then before 04:30 in that case, because there is "nothing to see there". Is this perhaps the case?
If not, can you post a screenshot here of the state when you are fully scrolled to the left?

**Comment by khushbuThakker** [comment]
Hello @dzolnai ,

Here, I am sharing you screenshot of with the real data from our backend, In that program -1 ->  start from	"program_start": "2020-06-06 00:26:52",
 	"program_end": "2020-06-06 01:29:57""

![SCREENN](https://user-images.githubusercontent.com/18696361/83941065-eb0caa00-a805-11ea-8321-c97e0d1f4ebb.png)

**Comment by meankit1990** [comment]
Hi Khushbu,

I guess you are trying to add data as per IST and the EPG Guide works on UTC Time. As you can see the timeline which is created for you is UTC+530. 

You can resolve your problem with Setting up the timezone.

**Comment by khushbuThakker** [comment]
Hi @meankit1990 ,
I already converted all the UTC time zone into the locale time zone. The issue is not based on timezone I think because I tried this with static data also but it's not working.

**Comment by meankit1990** [comment]
Hi,

I thought that could be the problem. When I implemented this library I faced the same issue and reason was due to this timezone conversion. Its working completely fine for me now.

I am not sure that what could be the problem in your case.

**Comment by dzolnai** [comment]
Hi @khushbuThakker,

First of all, the library is only supposed to work on Android TV, and you are testing on a mobile device. I can not guarantee that it will work there.
So you said that the `demo` app does also not work for you? What is the earliest time you can scroll to? Can you send a screenshot of that too? Make sure you have no changes in your code.
What timezone does the device have?

**Comment by teamandroidsudo** [comment]
Hello @dzolnai ,
Yes, I am trying to integrate this demo in my application but the problem is start timing in my channel is 12:00 AM and the end time is 23:00PM and in that channel, I have multiple programs where the length of the program is minimum 5 minutes.

So after you suggest me to change below parameter, I changed it in my code: 
private const val DAY_STARTS_AT_HOUR = 0
private const val DAY_ENDS_NEXT_DAY_AT_HOUR = 0

but still, there is no effect in the timeline.

I attached a screenshot in the above reply where my start time in the time bar is 5:30 AM.

It would be good if you can suggest some way to change timeline  so my program can be sync with the timeline

**Comment by khushbuThakker** [comment]
Hello @dzolnai ,
Yes, I am trying to integrate this demo in my application but the problem is start timing in my channel is 12:00 AM and the end time is 23:00 PM and in that channel, I have multiple programs where the length of the program is minimum 5 minutes.

So after you suggest me to change below parameter, I changed it in my code:
private const val DAY_STARTS_AT_HOUR = 0
private const val DAY_ENDS_NEXT_DAY_AT_HOUR = 0

but still, there is no effect in the timeline.

I attached a screenshot in the above reply where my start time in the time bar is 5:30 AM.

It would be good if you can suggest some way to change the timeline so my program can be sync with the timeline

**Comment by dzolnai** [comment]
The screenshot you attached is not of the demo.
I think that maybe you changed something else which might have broken the code.
Can you perhaps send me the source code?

**Comment by khushbuThakker** [comment]
Hello @dzolnai ,
I only passing my API response in this demo instead of static data which was in the library.
Is there any other way we could connect? because I am not allowed to share the source could as I integrated this demo in my project so.
It would be great if we can connect via twitter handler so I can show you what is changed in my code.

**Comment by dzolnai** [comment]
Feel free to send an email to daniel@egeniq.com
Maybe there is a way you could not use the API but some fake data where it still happens so you can share it with me?

**Comment by khushbuThakker** [comment]
Hello @dzolnai ,
The issue is about timezone conversion. Not with the library.
I am closing this issue.
Thank you the help

**Comment by dzolnai** [comment]
Okay, great that you have finally found the culprit!
If you have any other problems with the usage of the library, feel free to open a new issue.

**Comment by meankit1990** [comment]
@khushbuThakker  I told you so :)
