### ISSUE TITLE
"Jump To Live" & individual scrolling.

### ISSUE THREAD

**Issue by AnandRabari** [egeniq/android-tv-program-guide#13]
Hii there,

All thanks for this awesome library. The library is for a best use for tv program, but it is also working in mobile device for channel view. Now the issue, 

1.) I am facing the issue is whenever I do a horizontal scroll to shows of any individual channel then it will scroll that particular channel and not scrolling whole gridview. Now I want to make a scroll to whole gridview even if I  scroll any individual channel horizontally. 

2.) "Jump to live" button works properly in tv UI but if we scroll horizontally and at the same time if we press the button then after that it will not navigate us to the live programs.

Any guidance will be appreciable.

**Comment by dzolnai** [comment]
Hi!

First of all, thanks for using the library :)

Do you experience both issues on a mobile (non-TV) device?

**Comment by AnandRabari** [comment]
Yes, I have faced both issues on mobile(non-TV) device. Also, if we connect mouse to tv and just try to do same then we face both issues in tv also.

**Comment by NikhilUsadadiya** [comment]
Hello,

I also faced both this issue in mobile device. This works quite well in TV when we scroll or operate with remote but this not works well in mobile using touch scroll.

**Comment by dzolnai** [comment]
I'll try to fix this during the week, will come back to you if I have something ready.

**Comment by dzolnai** [comment]
Hi @AnandRabari and @NikhilUsadadiya,

I have checked your reports and I indeed see the same behaviour. 
However, I don't see an easy solution for fixing these. 
The library was built with keyboard navigation in mind, which is the default on Android TV, used almost exclusively.
The navigation part of the code is fully taken from the original source code, so the experts at Google have built it like this on purpose.
If you can solve it yourselves, you can make a pull request and I will gladly review it and merge it if it is OK, but I will not be able to solve this for you.

**Comment by NikhilUsadadiya** [comment]
Ok. Let's try to resolve this. But can you help me to figure out that is there any particular method to scroll a row in recycler or smoothscroll is working for it?  @dzolnai

**Comment by dzolnai** [comment]
Well this is how it works currently:

When you go left or right, it will trigger the `focusSearch` method of `ProgramGuideRowGridView`.
In that method, it checks if the row should be scrolled or not. If yes, it will call the `scrollByTime()` method.
That will call the `shiftTime` method of `ProgramGuideManager`, which will do a callback to the fragment (`onTimeRangeUpdated`).
That will scroll the timeline row (`timeRow?.scrollTo`), which will scroll all other rows as well (you can check this by dragging the timeline row with your mouse, it will scroll all other rows as well).

**Comment by NikhilUsadadiya** [comment]
Okk let me check it once. Thanks for the guidance @dzolnai

**Comment by NikhilUsadadiya** [comment]
Hey @dzolnai 
Among the above 2 issues, I resolved one of them. "Jump To Live" issue for mobile device is resolved and tested well in my code but I didn't get any way for the second one. Can you just guide me, like from where the whole gridview is scrolling horizontally when we scroll timerow horizontally? I make changes in ProgramGuideFragment.kt but failed. If possible, guide me for this in your free time.

Regards,
Nikhil

**Comment by dzolnai** [comment]
Hi,

So when you go left or right in one of the rows with the keyboard, it will call `ProgramGuideRowGridView.focusSearch()`.
That will determine if it just needs to jump to the next focused view, or it also needs to scroll the whole view.
If that has to be done, it will call `scrollByTime()` with a delta time change (+ for forward, - for backward). Scroll by time will then shift the time on the manager, which will then call `notifyTimeRangeUpdated()`.
The fragment is subscribed to these updates event, so `ProgramGuideFragment.onTimeRangeUpdated()` will be called.
That will calculate how many pixels should be scrolled, and calls `timeRow.scrollTo(scrollOffset, true)`.

When the fragment was created, in `setupComponents()`, we have created an `onScrollListener`, which calls `onHorizontalScrolled()` when the `timeRow` scrolls. So this method will be called, and will call `scrollBy()` on each of the rows of the grid.

**Comment by NikhilUsadadiya** [comment]
Okk. I will check this flow & try to make it resolve for the mobile device. Thanks.
