### ISSUE TITLE
Open specific channel position

### ISSUE THREAD

**Issue by TagorePde** [egeniq/android-tv-program-guide#14]
Hello, I want to go to a specific channel when EPG fragment is opened (scroll to that channel), how can I achieve this?
Regards.

**Comment by dzolnai** [comment]
Hi, you can use the `scrollToChannelWithId(channelId)` method for that.

Example (in your own EpgFragment.kt):

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        programGuideGrid.addOnChildAttachStateChangeListener(object : RecyclerView.OnChildAttachStateChangeListener {
            override fun onChildViewDetachedFromWindow(view: View) {
                // Not needed
            }

            override fun onChildViewAttachedToWindow(view: View) {
                programGuideGrid.removeOnChildAttachStateChangeListener(this)
                scrollToChannelWithId("tv-nova")
            }
        })
    }

**Comment by TagorePde** [comment]
Hi, thanks for your answer, I tested and works, but when I use scrollToChannelWithId it is scrolled OK, but, how can I select an specific channel? it is not selected.

Best Regards

**Comment by muhammetfaik** [comment]
I add EpgFragment.kt file this code: 
```kotlin
  override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        programGuideGrid.addOnChildAttachStateChangeListener(object : RecyclerView.OnChildAttachStateChangeListener {
            override fun onChildViewDetachedFromWindow(view: View) {
                // Not needed
            }

            override fun onChildViewAttachedToWindow(view: View) {
                programGuideGrid.removeOnChildAttachStateChangeListener(this)
                scrollToChannelWithId("tv-nova")
            }
        })
    }
```
bu I have two function syntax error: `addOnChildAttachStateChangeListener` and `removeOnChildAttachStateChangeListener`
Can you help me ? @dzolnai and @TagorePde

**Comment by dzolnai** [comment]
What is the exact error you are getting from the compiler?

**Comment by muhammetfaik** [comment]
Unresolved reference 'addOnChildAttachStateChangeListener'. Unresolved reference 'removeOnChildAttachStateChangeListener'.
Cannot access 'VerticalGridView' which is a supertype of 'ProgramGuideGridView'. Check your module classpath for missing or conflicting dependencies.

**Comment by dzolnai** [comment]
There's something wrong with your project setup and the inclusion of the library, I cannot help with that.

**Comment by muhammetfaik** [comment]
I add library like your repo.Its not a wrong

**Comment by muhammetfaik** [comment]
thanks I fixed it
