### ISSUE TITLE
Scrolling in RTL mode not working properly

### ISSUE THREAD

**Issue by theapache64** [egeniq/android-tv-program-guide#15]
- :eye: [rtl_issue.mp4](https://drive.google.com/file/d/17CZA_C85eb9gRdCKvK9oIirZPUTis-BI/view?usp=sharing)

## Steps to Reproduce

- Clone repo
- Go to developer option and turn on `Force RTL`
- Run the project

Can you guys tell me how can I fix this issue?

**Comment by theapache64** [comment]
Gentle Reminder  :bell:

**Comment by dzolnai** [comment]
Hi! I'm currently on vacation, I can have a look on Monday.

**Comment by theapache64** [comment]
Alright :smiley: Thanks man

**Comment by dzolnai** [comment]
I see the issue, it will probably require multiple smaller fixes through the code.
I assume that in RTL mode, the timeline and channel column should look exactly the same as in non-RTL mode. Only the text in the program blocks should start on the right side instead of left.
And maybe for the detail view, the image should be on the right side, and the text labels to the left of it.
Let me know if you have suggestions.

**Comment by anoopmaddasseri** [comment]
Hey @dzolnai, Thank you for the quick response. I appreciate it. 👍   

I believe the RTL layout direction works perfectly as you can see in the attached video. The major issue I observe is with scrolling and focus, The program blocks don't scroll properly when traverses through the program's ( focus-walk ) in RTL. I believe Text RTL support we can address replacing the "**left/right**" layout properties to new "**start/end**" equivalents. Looking forwards, Thanks.

> And maybe for the detail view, the image should be on the right side, and the text labels to the left of it. 👍  

**FYR** - 

![image](https://user-images.githubusercontent.com/16607998/91146129-1780e580-e6d4-11ea-86a9-25b1d7d44936.png)

**Comment by anoopmaddasseri** [comment]
Hello @dzolnai, Gentle Reminder 🔔

**Comment by dzolnai** [comment]
Hello @anoopmaddasseri, @theapache64, @sathyajithrdev,

I've just pushed a commit to this repo, fixing the RTL issues, mainly with focus and navigation.
From what I've read, timelines should not be reverted in RTL mode, so I kept the original timeline there.
That means that the grid below and the channel view are also in the original layout (LTR).
The detail view below the grid, and the toggles above are all changed to RTL mode.

Hope it works for you now, please reopen if you see any issues.

**Comment by anoopmaddasseri** [comment]
@dzolnai Great work, thank you for the support. I'll check and get back to you. 👍 💯

**Comment by anoopmaddasseri** [comment]
> From what I've read, timelines should not be reverted in RTL mode, so I kept the original timeline there.

Hi @dzolnai,  Could you please provide some references for finding ☝️?

**Comment by dzolnai** [comment]
[See this Apple developer page](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/SupportingRight-To-LeftLanguages/SupportingRight-To-LeftLanguages.html).
Relevant sentences:

> Types of controls and content that should not flip in a right-to-left language are:
> - Video controls and timeline indicators

**Comment by anoopmaddasseri** [comment]
@dzolnai I have verified the behavior of [Google Live Channels App](https://play.google.com/store/apps/details?id=com.google.android.tv&hl=en_IN) from play store. Timeline indicators stay in the original layout (LTR). The channel list flips in right-to-left. Please find the attachment for your reference. Also attaching the screenshot from [Saudi Arabia OSN™](https://www.osn.com/ar-sa/watch/tv-schedule) for Arabic language reference, in which timeline also flips but I think it doesn't make sense in the case of mobile & TV device as you pointed out. Thanks, Looking forward 👍 

**Google Live Channels SS:**

![image](https://user-images.githubusercontent.com/16607998/92127135-a0a7c300-ee1e-11ea-88e6-a4a116ef2952.png)

**Saudi Arabia OSN™ Web SS:**

![image (1)](https://user-images.githubusercontent.com/16607998/92127282-c92fbd00-ee1e-11ea-889d-b8b14288e0b2.png)

**Comment by anoopmaddasseri** [comment]
@dzolnai My bad. updated the observation, Please check 👉 - https://github.com/egeniq/android-tv-program-guide/issues/15#issuecomment-686526530. Thanks.

**Comment by dzolnai** [comment]
That means that we should flip them as well? :)

**Comment by anoopmaddasseri** [comment]
Indeed, IMO. 🙂

**Comment by theapache64** [comment]
@dzolnai Since we haven't fully fixed this issue, can you pls reopen this thread?

**Comment by dzolnai** [comment]
Update: I was busy today with making RTL scrolling work.
I have scrolling working, there are still some minor polishing things missing. Hopefully I can push the fix on Monday.

**Comment by anoopmaddasseri** [comment]
Awesome, Thanks for the update @dzolnai, Looking forwards. 👍

**Comment by dzolnai** [comment]
@anoopmaddasseri I have just pushed the commit with the fix. Please reopen if you see any issues.

**Comment by anoopmaddasseri** [comment]
Excellent stuff @dzolnai. Keep Up the Good Work, Terrific! 🥇 💯
