### ISSUE TITLE
Possibility of lazy loading

### ISSUE THREAD

**Issue by meankit1990** [egeniq/android-tv-program-guide#19]
Hi,

Thanks for this amazing library. It works perfect for me. I just needed to check that if there is any possibility that we can load data on scroll rather than we just all the EPG data at once.

My current scenarios is that I need to load epg for Next 7 days but that takes a lot of time to populate. So Can you please help me with that how can I load the epg day by day as soon as that's available from API.

Thanks in advance.

**Comment by dzolnai** [comment]
Hi Ankit,

You should only load one day's worth of data into the library when the fragment calls `requestingProgramGuideFor(date)`
You make a request for that single day then, and load it into the grid.

See the method here: https://github.com/egeniq/android-tv-program-guide/blob/6e59051ea9ad45e027a6f888f78e590a40f91096/demo/src/main/java/com/egeniq/programguide/EpgFragment.kt#L92

**Comment by meankit1990** [comment]
That's what I am already doing... What if I need to load more than a day's data in the epg one after another. So that I can scroll though next days as well without changing the date/day from the dropdown.

**Comment by dzolnai** [comment]
I'm sorry but that's not supported. You could extend the hours which should work, maybe you need a few modifications here and there. But it will not load the items lazily for you.

**Comment by meankit1990** [comment]
Yeah extending the hours are working fine for me... Like if I load all 7 days data at once than there is no issues... Its just when loading the data one after another is not happening.

**Comment by dzolnai** [comment]
There's no support for that in the library, it would be quite complicated to extend it as well. Feel free to try it though, PRs are always welcome :)

**Comment by meankit1990** [comment]
Sure.... I'll try and will send a PR if that works for me :)

**Comment by joecizac** [comment]
First of all, thank you a ton @dzolnai for this brilliant library. :heart: 
@meankit1990 basically you want to apply pagination to the EPG right? Meaning gracefully fetching the next smaller chunk of data from the API when you near the end of scroll instead of pre-fetching all data which is heavy. I am facing the same dilemma. 
Any luck though? :worried:

**Comment by meankit1990** [comment]
@joecizac I couldn't do it that gracefully but was able to load data day by day. But on each day load focus just goes to first event.

**Comment by joecizac** [comment]
Got it :+1:
I will update if I come up with some changes for the EPG to support pagination :wink:
