### ISSUE TITLE
Dynamic channel selector.

### ISSUE THREAD

**Issue by NikhilUsadadiya** [egeniq/android-tv-program-guide#20]
Hello Daniel,

Again I am here to bother you :) Here I want to know that is there any way to highlight the channel block. 
Explanation:- When we navigate the shows using remote it will highlight it and informs the user that at which show the cursor or remote controller is. Same ways if we scroll vertically then again the remote controller movement and selected shows highlighted. Now during vertical scroll, I want to highlight the channel also that currently, which channel is selected.

Image:- https://drive.google.com/file/d/1y9It6Gvi1TjLxrWEEvELrYw402hl_yKD/view?usp=sharing

Thanks & Regards,
Nikhil,

**Comment by dzolnai** [comment]
Hi,

I've pushed a commit which enabled this feature.
Please reopen if you see any issues with it.

Cheers,
Daniel

**Comment by NikhilUsadadiya** [comment]
Hii,

Its working in your latest push. Can you tell me in which classes did you make changes?


Regards,
Nikhil

**Comment by dzolnai** [comment]
Hi, just check the latest commit.

**Comment by NikhilUsadadiya** [comment]
Yeah, I got the changes. Thanks Daniel.
