### ISSUE TITLE
play stream onScheduleSelected 

### ISSUE THREAD

**Issue by Matador2020** [egeniq/android-tv-program-guide#22]
_Thank you for your great work, the guide is excellent._

I want to know if it possible to display the stream instead of the image at the bottom of the screen on the left onScheduleSelected ? 
is there a way to do it?

**Comment by meankit1990** [comment]
@Matador2020  Yes you can... I have modified this library as per my on convenience. All you need to do is create your on player and change the stream onScheduleSelected. Just you need to check that it should be changed when you change the row (Channel) not the Column(Event).

**Comment by Matador2020** [comment]
Great thanks
