### ISSUE TITLE
Support for EPG channel page switching

### ISSUE THREAD

**Issue by anoopmaddasseri** [egeniq/android-tv-program-guide#23]
Hello @dzolnai,

Can we add support for the channel page switching with the channel up/down key? On TV remotes, increments/decrements the EPG channel. So if u see channels 1-5 now when u press channel down you should show channel 6-10.

- [KEYCODE_CHANNEL_UP](https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_CHANNEL_UP)
- [KEYCODE_CHANNEL_DOWN](https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_CHANNEL_DOWN)

Thanks.

**Comment by anoopmaddasseri** [comment]
@dzolnai https://developer.android.com/reference/android/app/Instrumentation#sendKeyDownUpSync(int)

**Comment by dzolnai** [comment]
I have added this feature in my latest commit. It is turned **off** by default because I can imagine not everyone would like to have it. You can enable it like this:

```
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        ...
        programGuideGrid.featureNavigateWithChannelKeys = true
    }
```
