### ISSUE TITLE
Progress bars display the progress  on non-broadcast time

### ISSUE THREAD

**Issue by duongtainhan** [egeniq/android-tv-program-guide#26]
Hello @dzolnai,
I think this is a bug that appeared when I changed some parameters in the original demo.

- I changed `DAY_STARTS_AT_HOUR` to 0, `DAY_ENDS_NEXT_DAY_AT_HOUR` to 6.
- And I changed min, max length:
`val MIN_SHOW_LENGTH_SECONDS = TimeUnit.MINUTES.toSeconds(5)`
`val MAX_SHOW_LENGTH_SECONDS = TimeUnit.MINUTES.toSeconds(60)`

I have tested on real device and an emulator. Real Device: Sony Bravia 4K GB ATV3 (Android version 8.0.0) + emulator(Android TV 720p API 27)

![screen_issue](https://user-images.githubusercontent.com/40598538/103070270-c803e500-45f3-11eb-9a9a-a017ef785ec1.png)

**Comment by dzolnai** [comment]
Hi, this is not a bug, but I could understand if somebody does not want those.
You can easily hide them with a one-line change in `ProgramGuideItemView.kt`.
See this patch file for how to do that:
[gap_no_progress.patch.txt](https://github.com/egeniq/android-tv-program-guide/files/5746746/gap_no_progress.patch.txt)

**Comment by duongtainhan** [comment]
Hi, @dzolnai 
Thank you so much! It helps a lot.
