### ISSUE TITLE
Not able to build release of library - constructor Handler()' is deprecated

### ISSUE THREAD

**Issue by MatDah77** [egeniq/android-tv-program-guide#27]
Hi,

many thanks for developing this library!
I'm trying to build a release version of the library but Android Studio say's the constructor of Handler is deprecated and refuses to compile. Although it works in debug... Not sure if I'm doing something wrong here... :)

Here's the error message from Android Studio:
w: C:\AndroidProjects\android-tv-program-guide-master\library\src\main\java\com\egeniq\androidtvprogramguide\util\WeakHandler.kt: (54, 24): 'constructor Handler()' is deprecated. Deprecated in Java

**Comment by dzolnai** [comment]
Hi!

When I tried building a release version of the demo, I didn't get any error.
But anyways, I have ran Lint, and fixed all the bigger warnings. I also pushed this as a commit to master. Please check if you can build a release version now.

**Comment by MatDah77** [comment]
Thanks I really appreciate the help and the work you have done.
I'm now able to compile the release-build of the library, many thanks :)
