### ISSUE TITLE
Not able to call setState(State.Content) from Android TV java project

### ISSUE THREAD

**Issue by MatDah77** [egeniq/android-tv-program-guide#28]
Hi again,

I'm currently using the library from a Android TV project written in Java.
So far I'm able to show the ProgramGuideFragment inside my Android TV project and I'm now populating the channels and schedule. I believe I have to call setState(State.Content) in order to have the ProgramGuideFragment show the data (I'm also before this calling SetData)?
But it seems as if I'm not able to call setState(State.Content) or setState(State.Loading) from my Fragment which inherits from the ProgramGuideFragment. 

error: cannot find symbol setState(State.Content); (this compile error is shown when trying to compile my code)...

Perhaps I'm doing something wrong here? :)

Kind regards

/Mattias

**Comment by dzolnai** [comment]
Hi!

Since sealed classes don't have a perfect match in Java, they translate to a class which has static instances for the objects, and static classes with constructors for the data classes. So this is how you can use `setState()` when calling it from Java:

    // Set content state
    setState(State.Content.INSTANCE);
    // Set error state
    setState(new State.Error("Error message"));
    // Set loading state
    setState(State.Loading.INSTANCE);

**Comment by MatDah77** [comment]
Hi,

once again, many thanks for quick response and help.
I very much appreciate the help.

Kind regards
/Mattias
