### ISSUE TITLE
The issue in getting the current channel name.

### ISSUE THREAD

**Issue by arunoodles** [egeniq/android-tv-program-guide#30]
Hi,

I was not able to get the current channel name or channel position on the EPG fragment. Can you please help me resolve this issue?

**Comment by dzolnai** [comment]
Hi! What do you mean with current? The channel the currently selected program belongs to?

**Comment by arunoodles** [comment]
Yes, the current channels belong to the focused or selected program.

**Comment by dzolnai** [comment]
You could easily extend the program to incorporate the channel ID, which you then use to retrieve the channel from the manager. See this patch file which extends the demo with the functionality, and prints the channel to logcat when your selection changes.
[channel_patch.txt](https://github.com/egeniq/android-tv-program-guide/files/5849220/channel_patch.txt)

**Comment by arunoodles** [comment]
It is not working in my case, I did not get the channel name instead of I got Null value or Simple Channel Model String.

**Comment by dzolnai** [comment]
I'm sorry, but the issue must be with your code. Either the channel name is wrong when retrieving from the manager, or you set it incorrectly on the schedule item.

**Comment by arunoodles** [comment]
It resolved now, an idea from your patch text worked for me, Thanks a lot.

**Comment by dzolnai** [comment]
Glad it worked!
