### ISSUE TITLE
Scroll the center Program Guide Grid when move from right to left

### ISSUE THREAD

**Issue by duongtainhan** [egeniq/android-tv-program-guide#31]
Hi,

I'm looking for a way to scroll the center Program Guide Grid when move from right to left. Can you guys tell me how to do it?
Also there is a variable in `ProgramGuideGridView` I don't understand yet is `overlapStart` in line `it.overlapStart = it.resources.getDimensionPixelOffset(R.dimen.programguide_channel_column_width)`.  Can you explain to me what it is, please?

Thanks & Regards.

**Comment by duongtainhan** [comment]
> Can you be a bit more specific with what you want? You can move the entire grid using `ProgramGuideManager.jumpTo()` or `ProgramGuideManager.shiftTime()`
I want when scrolling, the focus item will be in the center of the recyclerView in grip view. Like this: 
![snap_center](https://user-images.githubusercontent.com/40598538/110452579-e740e780-80f7-11eb-932b-a7a135b6862c.gif)

> `overlapStart` is required for the focus finder. In the programs row, the programs can be behind the left channel column. When you want to focus the row, you don't want to put focus on the program behind that column, because the user won't see the higlight and will be lost. This overlapstart makes sure that on first focus, no program behind the column will be selected.
Thanks for the explanation for me to understand. It helps a lot.

**Comment by duongtainhan** [comment]
I want when scrolling, the focus item will be in the center of recycler view. Like this: 
![snap_center](https://user-images.githubusercontent.com/40598538/110453341-a72e3480-80f8-11eb-8c98-e09216d238e7.gif)

**Comment by duongtainhan** [comment]
> `overlapStart` is required for the focus finder. In the programs row, the programs can be behind the left channel column. When you want to focus the row, you don't want to put focus on the program behind that column, because the user won't see the higlight and will be lost. This overlapstart makes sure that on first focus, no program behind the column will be selected.

Thanks for the explanation for me to understand. It helps a lot.

**Comment by duongtainhan** [comment]
> Can you be a bit more specific with what you want? You can move the entire grid using `ProgramGuideManager.jumpTo()` or `ProgramGuideManager.shiftTime()`


I want when scrolling, the focus item will be in the center of recycler view. Like this:

https://user-images.githubusercontent.com/40598538/110455222-bf06b800-80fa-11eb-8c6a-3fb49f5b81e2.mp4

**Comment by dzolnai** [comment]
I see, that is quite difficult to change, I do not have the time to do that.
You can try yourself, basically you need to change the `focusSearch(...)` method of `ProgramGuideRowGridView`, by calling scrollByTime at the correct time with the correct amount.

**Comment by duongtainhan** [comment]
> I see, that is quite difficult to change, I do not have the time to do that.
> You can try yourself, basically you need to change the `focusSearch(...)` method of `ProgramGuideRowGridView`, by calling scrollByTime at the correct time with the correct amount.

Thanks for the suggestion to me. I will try handling focusSearch.
