### ISSUE TITLE
Publishing on the official F-Droid repository

### ISSUE THREAD

**Issue by alexanderadam** [egeniq/android-tv-program-guide#37]
Would you consider adding android-tv-program-guide to the official F-Droid repository?
This way people would see it and can get updates easily.

There's also [some documentation on what is allowed](https://f-droid.org/en/docs/) but I guess it should be fine as long there are no proprietary extensions.
It's possible to [create a RFP on the F-Droid GitLab repository](https://gitlab.com/fdroid/rfp/-/issues/new).

I only found [TVHguide](https://f-droid.org/en/packages/org.tvheadend.tvhguide/) but android-tv-program-guide seem to be missing.

**Comment by dzolnai** [comment]
Hi!

I don't understand your request, this is a library, not an application you can use individually. It does contain a demo application, but that one shows dummy data, and would be of no use for regular users.

**Comment by alexanderadam** [comment]
Ah okay, I wasn't aware of that.
