### ISSUE TITLE
Support for the program to be focused instead of scrolling and focusing

### ISSUE THREAD

**Issue by hruship0099** [egeniq/android-tv-program-guide#38]
Hi,
   Can we set the current program focused when ever we open the EPG without scrolling and focused. 
jumpTo method is scrolling. For my project requirement, it should be focused without scrolling. 

Thanks

**Comment by hruship0099** [comment]
@johankool In the below video, you can find when you click on jumpToLive button grid is scrolling and focus is setting. Can we directly focus program instead of scrolling and setting focus.

[Video ref](https://drive.google.com/file/d/1NlxePY7eF7HxwgzPweGPfp0LY2AZbo7I/view?usp=drivesdk)

**Comment by dzolnai** [comment]
@hruship0099 do you mean that the timeline should jump immediately instead of visibly scroll?

**Comment by hruship0099** [comment]
Yes @dzolnai

**Comment by dzolnai** [comment]
Here's a diff file which achieves that, you can execute it on the latest version of the develop branch: `git apply dont_animate_jump_to_live.txt `.
I don't believe this should be a feature of the project (unless more people ask for it), but you can freely add it to your own fork.
[dont_animate_jump_to_live.txt](https://github.com/egeniq/android-tv-program-guide/files/9525762/dont_animate_jump_to_live.txt)

Let me know if this works for you.

**Comment by hruship0099** [comment]
@dzolnai thank you, I will check and revert.

**Comment by hruship0099** [comment]
@dzolnai Its working after the change. Thank you very much for your support and for your library.
