### ISSUE TITLE
Unable to focus short programs in EPG from autoScrollToBestProgram

### ISSUE THREAD

**Issue by hruship0099** [egeniq/android-tv-program-guide#39]
Hi,
  Omn opening of EPG When ever I try to focus the short program for a specific channel, focus is moving to next program. 

Pl. help me in resolving this

**Comment by dzolnai** [comment]
Hi, did you make any changes to the project, or is this with the demo?

**Comment by hruship0099** [comment]
@dzolnai It's happening with demo too. If current program is of shorter length, if you scroll to future program and on click of jump to live, current program is not focused. Instead program next to it is being focused.[Video ref](https://drive.google.com/file/d/1NlxePY7eF7HxwgzPweGPfp0LY2AZbo7I/view?usp=drivesdk)

**Comment by hruship0099** [comment]
@dzolnai Can you please update on this?

**Comment by dzolnai** [comment]
@hruship0099 what device / emulator did this happen on?

**Comment by hruship0099** [comment]
@dzolnai I am using ZTE manufactured STB with Android 10 version

**Comment by dzolnai** [comment]
@hruship0099 do I understand it correctly that the issue is that after clicking jump to live, it focuses the wrong program?

**Comment by hruship0099** [comment]
yes @dzolnai its focusing wrong program instead of current one.

**Comment by dzolnai** [comment]
Fixed by #40

**Comment by hruship0099** [comment]
@dzolnai Its working after the change. Thank you very much for your support and for your library.
