### ISSUE TITLE
Updating EPG

### ISSUE THREAD

**Issue by Dule95D** [egeniq/android-tv-program-guide#4]
Hello! Just want to say, thank you for this great library. I'm forced to ask help here, because I have tried everything and no luck with this one. I have modified a little library and added function which will update row by row and that is working fine, but problem is that when update is finished, timeline is scrolled at the beginning. I will show you my code:

````
fun updateData(reverse: Boolean, count: Int) {
        val channelCount = programManager.channelCount
        if (!reverse) {
            for (i in (channelCount - count) until channelCount) {
                val listAdapter = ProgramGuideListAdapter(context.resources, programGuideHolder, i)
                if (reverse) {
                    programListAdapters.add(0, listAdapter)
                    notifyItemInserted(0)
                } else {
                    programListAdapters.add(listAdapter)
                    notifyItemInserted(programListAdapters.size)
                }
            }
        } else {
            for (i in count - 1 downTo 0) {
                val listAdapter = ProgramGuideListAdapter(context.resources, programGuideHolder, i)
                if (reverse) {
                    programListAdapters.add(0, listAdapter)
                    notifyItemInserted(0)
                } else {
                    programListAdapters.add(listAdapter)
                    notifyItemInserted(programListAdapters.size)
                }
            }
        }
    }

````

Also I have tried to comment this functions `updateTimeline()`, `autoScrollToBestProgramme()`, but no luck.

**Comment by dzolnai** [comment]
Hi! First of all, thanks for using the library.

It is kind of hard to determine where it goes wrong, would you be able to push an example somewhere, in which this can be reproduced?

If not, I would put a breakpoint in `ProgramGuideFragment::onHorizontalScrolled()`. That is triggered when it scrolls anywhere. Maybe you can see then in the call stack what triggers it.

**Comment by Dule95D** [comment]
Hi @dzolnai, thank you for quick response! I will try to debug there and see what happens. Thanks anyway, Will let you know what I have discovered.

**Comment by Dule95D** [comment]
Hi @dzolnai! Solved it now, but another problem appeared. Scroll doesn't move when new data is loaded, but when I try to go left, scroll won't move with focus on left. To fix it I need to go move right and then it will work and I will see cards which were behind. After new data loaded again, the same will happen.

**Comment by dzolnai** [comment]
Hi, good to hear that the original issue has been solved :)
I think the issue is that focus has jumped to another view on the screen (such as the focus catcher), and it does not jump back on the RecyclerView.
If you enable 'Show layout bounds' in developer settings of the TV, you can see the current focus, because there is a blue X on it. Maybe that helps you seeing who has taken the focus.
In `ProgramGuideFragment::onTimeRangeUpdated()` you can see an interaction like this from line 519 to 529.
This is required because the focus will jump around if I don't disable focus on the RecyclerView. I put it on the focus catcher while the view is scrolling so that I know where the focus went instead of letting it jump on a random view on the screen. When scrolling is done, I put it back on the RecyclerView.
I hope this helps you finding the issue.

**Comment by Dule95D** [comment]
Hi @dzolnai, thanks again for being so quick! Maybe I didn't explain exactly what is the problem. Focus stay inside recyclerview and which is great, stay on the same card and the time is for example 13:00 and you have some shows behind and in future. If you go in future, focus will move on right and the card will be centered always, but if you go behind the scroll won't move and you will not see the focus also. This is probably because I added this in function `updateTimeline()`

```
private fun updateTimeline(update: Boolean) {
        timelineStartMillis = ProgramGuideUtil.floorTime(programGuideManager.getStartTime() - MIN_DURATION_FROM_START_TIME_TO_CURRENT_TIME, HALF_HOUR_IN_MILLIS)
        val timelineDifference = programGuideManager.getStartTime() - timelineStartMillis
        timelineAdjustmentPixels = ProgramGuideUtil.convertMillisToPixel(timelineDifference)
        Log.i(TAG, "Adjusting timeline with ${timelineAdjustmentPixels}px, for a difference of ${timelineDifference / 60_000f} minutes.")
        timeRow?.let { timelineRow ->
            (timelineRow.adapter as? ProgramGuideTimeListAdapter)?.let { adapter ->
                adapter.update(timelineStartMillis, timelineAdjustmentPixels)
                for (i in 0 until programGuideGrid.childCount) {
                    programGuideGrid.getChildAt(i)?.let {
                        if (it.findViewById<RecyclerView>(R.id.row) != null && !update) {
                            (it.findViewById<RecyclerView>(R.id.row).layoutManager as LinearLayoutManager).scrollToPosition(0)
                        }
                    }
                }
                if (!update) {
                    timelineRow.resetScroll()
                }
            }
        }
}
```

As you can see, I have added this flag update, so if I'm updating EPG, I don't want to scroll to zero position. I have added also in this function 

```
override fun onTimeRangeUpdated(update: Boolean) {
        val scrollOffset = (widthPerHour * programGuideManager.getShiftedTime() / HOUR_IN_MILLIS).toInt()
        Log.v(TAG, "Scrolling program guide with ${scrollOffset}px.")
        if (timeRow?.layoutManager?.childCount == 0 || isInitialScroll) {
            isInitialScroll = false
            if (!update) {
                timeRow?.post {
                    timeRow?.scrollTo(scrollOffset, false)
                }
            }
        } else {
            if (!programGuideGrid.hasFocus()) {
                // We will temporarily catch the focus, so that the program guide does not focus on all the views while it is scrolling.
                // This is better for performance, and also avoids a bug where the focused view would be out of scope.
                focusEnabledScrollListener?.let {
                    timeRow?.removeOnScrollListener(it)
                }
                focusCatcher?.visibility = View.VISIBLE
                focusCatcher?.requestFocus()
                programGuideGrid.descendantFocusability = ViewGroup.FOCUS_BLOCK_DESCENDANTS
                focusEnabledScrollListener = object : RecyclerView.OnScrollListener() {
                    override fun onScrollStateChanged(recyclerView: RecyclerView, newState: Int) {
                        if (newState == RecyclerView.SCROLL_STATE_IDLE) {
                            programGuideGrid.descendantFocusability = ViewGroup.FOCUS_BEFORE_DESCENDANTS
                            timeRow?.removeOnScrollListener(this)
                            focusEnabledScrollListener = null
                            programGuideGrid.requestFocus()
                            focusCatcher?.visibility = View.GONE
                            updateCurrentTimeIndicator()
                        }
                    }
                }.also { timeRow?.addOnScrollListener(it) }
            }
            if (!update) {
                timeRow?.scrollTo(scrollOffset, true)
            }
        }
        // Might just be a reset
        if (scrollOffset != 0) {
            updateTimeOfDayFilter()
            updateCurrentDateText()
        }
    }
```

**Comment by dzolnai** [comment]
Hi, if you could make a recording, that would be great!

**Comment by Dule95D** [comment]
https://streamable.com/fzqas

You will see at bottom progress (waiting for new data). After new data is added, I try to move right and then scroll go at the beginning. It would happen also if I try to move left. The scroll will go at the beginning.

**Comment by dzolnai** [comment]
I think the problem is in `onTimeRangeUpdated`.
You need to wrap the whole ` if (!programGuideGrid.hasFocus()) { ... }` part also in the `if (!update) { }` block. Because now we disable focus until the scrolling has completed. But since you don't scroll on update, it will be in weird state. Can you check if that solves it?

**Comment by Dule95D** [comment]
No, still the same issue. I have recorded one more video where you can see that you can go left, but when you go further you will not see the focus (that is not shown in video). But if you move right, the scroll will nevertheless move to left at 0 position.

https://streamable.com/d2qs2

**Comment by dzolnai** [comment]
Could you make a video where you have show layout bounds enabled please? Maybe that will shed some light onto what's going on.

**Comment by Dule95D** [comment]
https://streamable.com/x2jvg

Here I'm moving to left until i move to right the scroll won't go left

**Comment by Dule95D** [comment]
Hi @dzolnai! Fixed it! I have commented in update function this method `updateChannelsTimeRange`

**Comment by dzolnai** [comment]
Good to hear, I was already running out of ideas :) 👍

**Comment by jiomedia** [comment]
Hello @dzolnai  can you please post any solutions like how to load program infomation lost asynchronously. As like we collect dont huge data set at one go. For every channel we hit API and take information load them accordingly.
Please help

**Comment by vikrantThakur** [comment]
hello @dzolnai  i am using this library but the problem here is we need to load program information list asynchronously for each channel.
Is in the git repository example its showing whole data set of channels and program mapping given to epg at once.
I need to load data party and async.
Please help.

**Comment by dzolnai** [comment]
Hi!
Next time please create a new issue for unrelated questions, no need to notify other people in this discussion.
You can only update the EPG with all the channels together. So you will have to wait for all of your calls to finish, and then bundle the data together.
You can use RxJava or coroutines for that, but that's out of the scope of this library.
