### ISSUE TITLE
Timeline broken when returning from other fragment

### ISSUE THREAD

**Issue by ladamski1** [egeniq/android-tv-program-guide#41]
Hello @dzolnai 
I'm integrating your library with my application and I've found an issue with timeline row. It is reproducible in demo application.

In the method `EpgFragment.onScheduleClicked()` I'm opening a new fragment (it can be blank fragment) using this code: 
```
val transaction = activity?.supportFragmentManager?.beginTransaction()
transaction?.replace(R.id.fragment_container, BlankFragment())
transaction?.addToBackStack("blank")
transaction?.commit()
```
It opens the new blank fragment (in my app this is fragment with asset details). Then I want to return to `EpgFragment` by pressing back button. When I do this, the timeline on `EpgFragment` is moved by 4.5 hours and also `programguide_current_time_indicator` has a wrong position. For other DISPLAY_TIMEZONE setting, the time difference is different, but always not correct. I attached the screenshots to show this behaviour.

BEFORE (House of Cards starts at 11:09 and this is correct on the timeline)
![image](https://user-images.githubusercontent.com/113098087/189102183-fb00a002-c308-429e-a2d1-3cb5b297c30b.png)

OPENING NEW FRAGMENT
![image](https://user-images.githubusercontent.com/113098087/189102300-cb63363a-9768-4cf6-9d14-3f7fd1b4d889.png)

AFTER BACK BUTTON PRESSED (House of Cards starts at 11:09 but on the timeline it starts at 6:39)
![image](https://user-images.githubusercontent.com/113098087/189102419-a40baed0-47e6-4eb3-9e20-98e201ca39cf.png)

**Comment by ladamski1** [comment]
Can you reproduce this issue? Have any ideas how to fix it?

**Comment by dzolnai** [comment]
Hi @ladamski1, sorry for the late reply. This should be fixed on the main branch as of now, please let me know if you have any issues with it.

**Comment by ladamski1** [comment]
Thank you very much, now it's working great.
