### ISSUE TITLE
Support required in setting focus to the current time range programs on navigating up or down.

### ISSUE THREAD

**Issue by hruship0099** [egeniq/android-tv-program-guide#47]
hi @dzolnai 
  When navigating through the programs using up and down, current time range programs is not focusing instead previous or future programs are focusing.  Pl. find the video attachment
https://user-images.githubusercontent.com/8926002/214213070-e7168c5f-9a9f-498a-8d7a-e6c5515e5095.mp4

Can you pl. help me in resolving this. Thanks in advance

**Comment by dzolnai** [comment]
Hello @hruship0099 ,

Unless you can send a reproduction code, I cannot look into it.
Also, the video does not work for me.

**Comment by hruship0099** [comment]
Hi @dzolnai 
  Sorry for the late reply. 
Pl. find the latest video attachment below. Hope you are able to access this.
https://user-images.githubusercontent.com/8926002/216939364-4e672a15-94c6-496e-9888-ed9fc83ec5fc.mp4

In the video, you can observe like while performing down, some times program which is under current time range(have progress bar inside card) is not getting focused. Instead subsequent card is getting focused. 

Can you pl. help me in focusing current time range program on performing up/down.

I have made only small change in the library code programguide_item_row.xml. Pl. find the code below
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:focusable="false"
    android:orientation="horizontal"
    tools:ignore="RtlHardcoded">

    
    <com.egeniq.androidtvprogramguide.row.ProgramGuideRowGridView
        android:id="@+id/row"
        android:layout_width="match_parent"
        android:layout_height="@dimen/programguide_program_row_height_with_empty_space"
        android:clipToPadding="false"
        android:layout_marginStart="@dimen/programguide_channel_column_width"
        tools:ignore="RtlSymmetry" />

    <include
        layout="@layout/programguide_item_channel"
        android:layout_width="@dimen/programguide_channel_column_width"
        android:layout_height="@dimen/programguide_program_row_height_with_empty_space"
        android:layout_gravity="start" />


</FrameLayout>

**Comment by dzolnai** [comment]
Hello @hruship0099 
I see that you have replaced the padding with a margin in your example.
I don't recommend doing that, first of all, there's no visible change in the UI, but now the position calculations are broken, because they took that padding into account. If you really want to use a margin, you might have to change the focusing and position lookup code, but that will be quite complicated.

Cheers,
Daniel

**Comment by hruship0099** [comment]
Hi @dzolnai 

I understood that changing to margin will cause positions miscalculated.

Even after changing to padding instead of margin, I can see that with short duration programs, focus is not maintaining with current range programs. 

Pl. find the below video for reference.

https://user-images.githubusercontent.com/8926002/217782386-d45fe639-e1a7-4b50-9b21-7f4d1c752c2c.mp4

**Comment by dzolnai** [comment]
Ah I see what you mean.
That is not a feature of this repository.
The next program to focus is not based on the time, but on the position of the view. So if there are two views below it, it will select the one it is closer to, and not the one which is the currently playing program.
If you want this as a feature, you have to add it yourself. I can help you if you get stuck, but we do not have the time to implement such things, sorry.

**Comment by hruship0099** [comment]
Got it @dzolnai. 
Thanks again for your library.

**Comment by dzolnai** [comment]
You're welcome!
