### ISSUE TITLE
I want to use your skills in my java project

### ISSUE THREAD

**Issue by JeongHyeok97** [egeniq/android-tv-program-guide#49]
I am a Tv Player app developer. My senior developer told me that your epg format is very suitable for use in a tv app, and it will be written in java, so I tried to refer to your project. But it was code written in your Kotlin. Did you refactor the project that was implemented in Java through an update? If so, is there any way to refer to the project source of the previous Java version? It seems that there is no case other than you that implemented timeline and viewgroup control that changes according to time through Leanback. I would like help

**Comment by dzolnai** [comment]
Hello,
The original code was indeed written in Java, and is also linked from the readme of the repo, [see here](https://android.googlesource.com/platform/packages/apps/TV/+/android-live-tv/src/com/android/tv/guide/).
However, that code assumes to get the channels from the TV itself, and also is a bit outdated, so it might get some time to get it to work for you.
Perhaps a better option is to just take this project, convert the Kotlin files one by one to Java and then fix the remaining issues where the converter did not do a good job. I think you could do that in a couple of hours.

**Comment by swinder0161** [comment]
hi @dzolnai,

and for everyone's reference, I have converted to java and uploaded to my fork https://github.com/swinder0161/android-tv-program-guide/tree/java

I hope this will help others too.

Thanks,
Swinder
