### ISSUE TITLE
Time line not sync with current time 

### ISSUE THREAD

**Issue by MaheshaCN24** [egeniq/android-tv-program-guide#50]
Hi, Sir Thank you for your contribution.

I am new to this android TV development, I know java I don't know kotlin, I modified your UI according to my requirement but now the timeline and current time are not syncing. can you help me to solve this issue, in the program you are using hardcoded data can you provide one example of how to get data from API to the program in kotlin for this EPG program?

**Comment by dzolnai** [comment]
Hi,

There's an issue with the Android TV emulators that if you resume a previously saved emulator, it won't update the time. The fix is to wipe the data of the emulator. If that is not your case, I cannot help you, since you made changes I don't know about.

Cheers,
Daniel

**Comment by MaheshaCN24** [comment]
I am checking with sony tv,  i am just added your layout inside another
layout the thing is that time line not syncing with the time zone in my
case i am from india time difference is +5:30 hours

I attached a file please find

**Comment by dzolnai** [comment]
You might want to try overriding the display timezone: 
https://github.com/egeniq/android-tv-program-guide/blob/c3016c41d28589c65529e35e61c97ef5af0c904a/library/src/main/java/com/egeniq/androidtvprogramguide/ProgramGuideFragment.kt#L92

**Comment by MaheshaCN24** [comment]
After overriding the display time zone, it's working well. But what happens if my app is used in any other country?

**Comment by dzolnai** [comment]
This EPG is intended for having channels for a single country.
So if you are outside the country, the times won't change, even if you are in a different timezone.

**Comment by iqappdev** [comment]
> After overriding the display time zone, it's working well. But what happens if my app is used in any other country?

You can achieve it by offsetting the time zone to system time zone, I am getting the EPG in UTC time zone


`val timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss")
                                                val localTime = LocalTime.parse(ChnlEpgDetails[j].startTime, timeFormatter)
                                                val programStartTimeUTC = ZonedDateTime.of(
                                                    nextTime.toLocalDate(),
                                                    localTime,
                                                    ZoneOffset.UTC
                                                )

                                                // Convert the program start time to the system's default time zone
                                                val programStartTime = programStartTimeUTC.withZoneSameInstant(ZoneId.systemDefault())

                                                // Calculate the program end time
                                                val programEndTime = programStartTime.plusMinutes(ChnlEpgDetails[j].programDuration.toLong())`
