### ISSUE TITLE
not able to refresh data with new schedule list

### ISSUE THREAD

**Issue by MaheshaCN24** [egeniq/android-tv-program-guide#53]
Hi Sir,

i removed day filters and added 3 filter buttons, on clicking each button will fetch different  data from api and I passed required values to createschedule method  and it is working fine, but here my problem is how i can load the new schedule list data to adapter.

**Comment by dzolnai** [comment]
Hello, use first setData() and then setState(State.Content)
Example: https://github.com/egeniq/android-tv-program-guide/blob/master/demo/src/main/java/com/egeniq/programguide/EpgFragment.kt#L214

**Comment by MaheshaCN24** [comment]
I am calling API from epgFragment, I set the click listener in programguide fragment, i am passing filter parameter trough the refresh method please look at the code. 
please find the attachment 

[EpgFragment.txt](https://github.com/egeniq/android-tv-program-guide/files/11229432/EpgFragment.txt)
[programGuideFragment.txt](https://github.com/egeniq/android-tv-program-guide/files/11229433/programGuideFragment.txt)
