### ISSUE TITLE
current program view not updating currectly

### ISSUE THREAD

**Issue by MaheshaCN24** [egeniq/android-tv-program-guide#54]
Hi Sir,

the current program is not showing when opening the epg, which means that the program is scrolled to the left side with timeline and it is not visible. we have to use remote to navigate back to current program.
how to fix this problem?

**Comment by dzolnai** [comment]
Hello @MaheshaCN24 .
It seems to me that your time or timezone is off, or the scrolling timeline might have a bug.
I can only look into this if you can send me your code.

**Comment by MaheshaCN24** [comment]
Thank you for your support it is working now.
