### ISSUE TITLE
How to Set time to 12 hour Format

### ISSUE THREAD

**Issue by MaheshaCN24** [egeniq/android-tv-program-guide#55]
Hi Sir,
I need to set that timeline time in 12 hours format how can I do this?

**Comment by dzolnai** [comment]
Hello,

sorry for the late reply. Change `H:mm` to `h:mm` here:

https://github.com/egeniq/android-tv-program-guide/blob/ee45f61357e56345824e88b7ed5b2889a06c6492/library/src/main/java/com/egeniq/androidtvprogramguide/timeline/ProgramGuideTimeListAdapter.kt#L45
