### ISSUE TITLE
Date field is not updating immediately on scroll of programs

### ISSUE THREAD

**Issue by hruship0099** [egeniq/android-tv-program-guide#58]
hi @dzolnai 
   While scrolling programs right, once the next programs are loaded and on focus, date is not getting updated immediately. Date is getting updated after scrolling some more programs.

Please find the video for reference.
https://drive.google.com/file/d/1pxJBTlT22q2zCFt0vFbsLu57ujr92YPC/view?usp=sharing

Request your help to know how it can be fixed

**Comment by dzolnai** [comment]
Hello @hruship0099 this is not a bug, the date is not dependent on the selected program, but on the times in the top bar.
So until you see an hour less than 0:00 in the top bar, it will show yesterdays date

**Comment by hruship0099** [comment]
@dzolnai 
Got it, thank you.
