### ISSUE TITLE
Java implementation needed

### ISSUE THREAD

**Issue by swinder0161** [egeniq/android-tv-program-guide#60]
Hi egeniq

Can you please share the same app and library in java?

Thanks in advance

**Comment by dzolnai** [comment]
Hello, 
This has been asked before (https://github.com/egeniq/android-tv-program-guide/issues/49#issuecomment-1465693737) the library is only available in Kotlin.
It shouldn't be too hard to generate an aar from this, and use it as a library under your own project, or use it as a Kotlin submodule.

**Comment by swinder0161** [comment]
hi @dzolnai,

and for everyone's reference, I have converted to java and uploaded to my fork https://github.com/swinder0161/android-tv-program-guide/tree/java

I hope this will help others too.

Thanks,
Swinder

**Comment by dzolnai** [comment]
Thanks for your hard work, I have added a link to it in the readme of this repo!
