### ISSUE TITLE
Api to have 24-hour rolling window in grid view starting from previous half hour

### ISSUE THREAD

**Issue by swinder0161** [egeniq/android-tv-program-guide#61]
Does this kind of api already exist? if not, can you please help to code that quickly?

or else I can develop and contribute the same

**Comment by dzolnai** [comment]
Hello,

I think you could achieve something like that by reducing the programguide_table_width_per_hour dimension to something like 30-50dp perhaps.
But the content would be so crowded that you might run into some scroll or layout issues.

**Comment by swinder0161** [comment]
By rolling window I don't mean to show full 24hrs in 1 screen

I mean that the start of the grid view should be at last 30min time and
next 24 hours should be shown.

No history data needed, something like live TV without catch up.

Example:

If current time is 14Dec2023 1840
The grid view should show from 14Dec2023 1830 until 14Dec2023 1830

**Comment by dzolnai** [comment]
Oh like that. No we don't support that.

**Comment by swinder0161** [comment]
@dzolnai Will you have time to work on it?

I will do on this weekend if not.

**Comment by swinder0161** [comment]
here is the patch for this feature. It is in Java. You can help to convert to kotlin when have time

[ROLLING_WINDOW_HOURS.patch](https://github.com/egeniq/android-tv-program-guide/files/13691412/ROLLING_WINDOW_HOURS.patch)

**Comment by kiskala** [comment]
Hello! Can someone convert it to a downloadable application? Because I really need it. The android tv tv application is very slow and bad. I would even buy it on Google Play. Thanks: Peter

**Comment by kiskala** [comment]
That's what I thought 
https://github.com/egeniq/android-tv-program-guide

**Comment by swinder0161** [comment]
@kiskala For a Android/Google TV app, you can email me at swinder0161@gmail.com

I have a fully developed Google TV Video playback app which can take m3u playlist to make a full TV channels directory and EPG.

**Comment by kiskala** [comment]
Hello! I need an application that replaces the factory TV application,
which does not depend on the Internet, but receives the signal via coax
cable, but the factory application of JVC TV is very bad.

swinder0161 ***@***.***> ezt írta (időpont: 2024. febr. 29.,
Cs 17:16):

**Comment by swinder0161** [comment]
Then this is not the app you are looking for.

This project is only the EPG fragment.

I have used this project in my IPTV app.
