### ISSUE TITLE
Android TV Program Guide

### ISSUE THREAD

**Issue by kiskala** [egeniq/android-tv-program-guide#65]
Hello.  I am contacting you with a request.  Android TV Program Guide someone make this into a usable installable application.  I live in Hungary and am a Digi cable subscriber.  I bought a Jvc tv running Android Tv OS with a very bad system.  I want to disable the TV application running on it with this.  I don't know how to write programs.  Thanks.  Peter

**Comment by dzolnai** [comment]
Hello Peter,
Sorry for my late reply. This repository does not take information from your broadcaster, but it is fed from the API of the implementing party.
What you are looking for, is I think the official Android TV live browser made by Google, which this repository is also based on: https://play.google.com/store/apps/details?id=com.google.android.tv&hl=en&gl=US

Cheers,
Daniel

**Comment by dzolnai** [comment]
Szia, valószínűleg magában a TV-be nem raktak elég gyors processzort / elég memóriát, így sok idő kell neki elvégezni a váltást. Gondolom más alkalmazásokkal is ugyanez a bajod lenne, illetve sejtem, hogy nem is fogod tudni lecserélni a gyári programot másikra, mert tiltja a rendszer. De sajnos nincs tapasztalatom ilyen téren, hogy biztosat tudjak mondani.
Sok sikert a további kereséssel.
Üdv,
Dani

**Comment by kiskala** [comment]
Köszi. Lehet el kellene adni!😀 De a sweet tv szép és gyors lehet az a
megoldás! Üdv.: Peti

Dániel Zolnai ***@***.***> ezt írta (időpont: 2024. ápr. 16.,
K 15:35):
