### ISSUE TITLE
Jetpack compose

### ISSUE THREAD

**Issue by alijamal6459** [egeniq/android-tv-program-guide#66]
Hello, I'm a beginner in coding using jetpack compose and was wondering if I am able to use this library in my project?

If so can anyone help me on how to do so or do I need to convert/migrate the epg library to compose.
Thanks

**Comment by ChetanPatelPlayBoxTV** [comment]
Hello @alijamal6459 @johankool @petercv  @all

anyone can help for how to integrate epg(Android tv program guide) library to jetpack compose ?

any suggestion or idea to achieve this solution?

Thanks

**Comment by dzolnai** [comment]
@ChetanPatelPlayBoxTV please don't spam the contributors of this repository.
Have a look at how you can integrate fragments inside a compose app: https://developer.android.com/develop/ui/compose/migrate/interoperability-apis/views-in-compose#fragments-in-compose
