### ISSUE TITLE
Need help with timeline and line LIVE

### ISSUE THREAD

**Issue by IvanAbakumov** [egeniq/android-tv-program-guide#67]
Thank you for this example. It would be great if it were a full-fledged library. However, I have an issue with the timeline and the live line. In my current implementation, the line LIVE shows the current time, but it is not correctly aligned with the timeline. Could you please advise me on where I can make the change this?

**Comment by dzolnai** [comment]
Perhaps you have some kind of timezone issue, make sure that all your data uses the same timezone, and you set it also on the library.
Also make sure that your device time is correct
