### ISSUE TITLE
While Video Length is Larger then It skipping the Row and focused changed to 3rd row.

### ISSUE THREAD

**Issue by chetan532** [egeniq/android-tv-program-guide#69]
https://github.com/user-attachments/assets/91244e74-e527-44b4-a047-8d34766c26fc

Here in video when my video length is larger then view then it skipping whole row. Can you please give me solution for this.

**Comment by dzolnai** [comment]
Could you make an example using the demo, where I could reproduce this. This seems indeed like a bug

**Comment by dzolnai** [comment]
Hello @chetan532,
I did some testing, and found an issue with long rows that it sometimes did not want to move the focus up or down between the rows. I'm not sure if this is the same issue, but other than that it works fine for me. If it still happens, can you reopen this issue with a reproduction project?

Cheers,
Daniel
