### ISSUE TITLE
Scroll issues

### ISSUE THREAD

**Issue by sureshqplay** [egeniq/android-tv-program-guide#71]
issue 1
If we do long press and go down and again long press go up, there is blank space between first row and time row.

issue 2
If we make the EPG fragment height half of the screen scroll jerks lot. focus and all going some where. If we make it full screen then looks better

**Comment by dzolnai** [comment]
I can see these issues happening, but cannot find an easy solutions for them. As a workaround, you could add a delay between the scrolls when doing a long press, allowing the app more time to create the row / scroll in the meantime.
