### ISSUE TITLE
Extend progress for past shows

### ISSUE THREAD

**Issue by Dule95D** [egeniq/android-tv-program-guide#8]
Hello,

Is it possible to extend progress to shows which are in past? Currently you can see progress on current shows, but I would like to make progress visible also on shows which are in past.

**Comment by dzolnai** [comment]
Hi, here's a patch file with the required changes to do that.
You can apply this on the master branch of the repo to see the changes in the demo immediately (use `git apply progress-past-shows.patch`).

The idea is that you supply a progress via the schedule, which you then set on the item in the view, and do not care about the live time.

Let me know if something is not clear, or if it does not work.

[progress-past-shows.patch.zip](https://github.com/egeniq/android-tv-program-guide/files/3997628/progress-past-shows.patch.zip)

**Comment by Dule95D** [comment]
Hi @dzolnai,

That helped a lot. Thank you very much!
